# This is a basic workflow to help you get started with Actions

name: quiche

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ quiche ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: quiche
        run: |
         sudo apt update -y
         sudo apt upgrade -y
         git clone --recursive https://github.com/cloudflare/quiche
         cd quiche
         ls
         cargo build --release --features ffi,pkg-config-meta,qlog
         mkdir deps/boringssl/src/lib
         sudo ln -vnf $(find target/release -name libcrypto.a -o -name libssl.a) deps/boringssl/src/lib/

      # Runs a set of commands using the runners shell
      - name: curl
        run: |
          cd ..
          git clone https://github.com/curl/curl
          cd curl
          autoreconf -fi
          ./configure LDFLAGS="-Wl,-rpath,/home/runner/work/curl-http3/curl-http3/quiche/target/release" --with-openssl=/home/runner/work/curl-http3/curl-http3/quiche/deps/boringssl/src --with-quiche=/home/runner/work/curl-http3/curl-http3/quiche/target/release
          make
          sudo make install
      - uses: actions/upload-artifact@v2
        with:
          name: curl
          path: /home/runner/work/curl-http3/curl-http3/curl
